include(
    ":app",
    ":database",
    ":domain",
    ":repository",
    ":test",
    ":test-ui",
    ":ui-app",
    ":ui-favourites",
    ":ui-iap",
    ":ui-livedata",
    ":ui-search",
    ":ui-settings",
    ":ui-web"
)
