version: 2
jobs:
  build:
    working_directory: ~/dublin-mapper
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx4g
    steps:
      - run:
          name: Update SDK
          command: |
            yes | sdkmanager --licenses || true
            sdkmanager "platform-tools" "platforms;android-29"
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "buildSrc/src/main/kotlin/Dependencies.kt" }}
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "buildSrc/src/main/kotlin/Dependencies.kt" }}
      - run:
          name: Run ktlint
          command: ./gradlew ktlint
      - run:
          name: Run unit tests
          command: ./gradlew test
