name: DubLink CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest

    env:
      TERM: dumb
      ORG_GRADLE_PROJECT_usr: ${{ secrets.ORG_GRADLE_PROJECT_usr }}
      ORG_GRADLE_PROJECT_key: ${{ secrets.ORG_GRADLE_PROJECT_key }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('buildSrc/src/main/kotlin/Dependencies.kt','**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build repository
      run: ./gradlew assembleDebug

    - name: Lint Kotlin
      run: ./gradlew ktlint

    - name: Lint Android
      run: ./gradlew lintDebug

    - name: Test and coverage report
      run: ./gradlew testCoverage

    - name: Upload coverage report
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.ORG_GRADLE_PROJECT_codecovToken }} -f "*-report.xml"
