name: DubLink CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest

    env:
      TERM: dumb
      ORG_GRADLE_PROJECT_usr: ${{ secrets.ORG_GRADLE_PROJECT_usr }}
      ORG_GRADLE_PROJECT_key: ${{ secrets.ORG_GRADLE_PROJECT_key }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('buildSrc/src/main/kotlin/Dependencies.kt','**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build repository
      run: ./gradlew assembleDebug

    - name: Lint Kotlin
      run: ./gradlew ktlint

    - name: Lint Android
      run: ./gradlew lintDebug

    - name: Test :app
      run: ./gradlew :app:testDebugUnitTest

    - name: Test :database
      run: ./gradlew :database:testDebugUnitTest

    - name: Test :domain
      run: ./gradlew :domain:test

    - name: Test :repository
      run: ./gradlew :repository:test

    - name: Test :ui-app
      run: ./gradlew :ui-app:testDebugUnitTest

    - name: Test :ui-favourites
      run: ./gradlew :ui-favourites:testDebugUnitTest

    - name: Test :ui-iap
      run: ./gradlew :ui-iap:testDebugUnitTest

    - name: Test :ui-livedata
      run: ./gradlew :ui-livedata:testDebugUnitTest

    - name: Test :ui-search
      run: ./gradlew :ui-search:testDebugUnitTest

    - name: Test :ui-settings
      run: ./gradlew :ui-settings:testDebugUnitTest

    - name: Test :ui-web
      run: ./gradlew :ui-web:testDebugUnitTest
