name: DubLink CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest

    env:
      TERM: dumb
      ORG_GRADLE_PROJECT_usr: ${{ secrets.ORG_GRADLE_PROJECT_usr }}
      ORG_GRADLE_PROJECT_key: ${{ secrets.ORG_GRADLE_PROJECT_key }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Kotlin Lint
      run: ./gradlew ktlint

    - name: Android Lint
      run: ./gradlew lintDebug

    - name: app unit test
      run: ./gradlew :app:testDebugUnitTest

    - name: database unit test
      run: ./gradlew :database:testDebugUnitTest

    - name: domain unit test
      run: ./gradlew :domain:test

    - name: repository unit test
      run: ./gradlew :repository:test

    - name: ui-app unit test
      run: ./gradlew :ui-app:testDebugUnitTest

    - name: ui-favourites unit test
      run: ./gradlew :ui-favourites:testDebugUnitTest

    - name: ui-iap unit test
      run: ./gradlew :ui-iap:testDebugUnitTest

    - name: ui-livedata unit test
      run: ./gradlew :ui-livedata:testDebugUnitTest

    - name: ui-search unit test
      run: ./gradlew :ui-search:testDebugUnitTest

    - name: ui-settings unit test
      run: ./gradlew :ui-settings:testDebugUnitTest

    - name: ui-web unit test
      run: ./gradlew :ui-web:testDebugUnitTest
